export const REGISTER_SUCCESSFUL = 'REGISTER_SUCCESSFUL';
export const REGISTER = 'REGISTER';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESSFUL = 'USER_LOGIN_SUCCESSFUL';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_COUNTRIES_SUCCESSFUL = 'FETCH_COUNTRIES_SUCCESSFUL';
export const FETCH_COUNTRIES_FAILED = 'FETCH_COUNTRIES_FAILED';

export const FETCH_REDEEM_CONFIGS = 'FETCH_REDEEM_CONFIGS';
export const FETCH_REDEEM_CONFIGS_SUCCESSFUL =
  'FETCH_REDEEM_CONFIGS_SUCCESSFUL';
export const FETCH_REDEEM_CONFIGS_FAILED = 'FETCH_REDEEM_CONFIGS_FAILED';

export const REDEEM_WITHDRAW = 'REDEEM_WITHDRAW';
export const REDEEM_WITHDRAW_SUCCESSFUL = 'REDEEM_WITHDRAW_SUCCESSFUL';
export const REDEEM_WITHDRAW_FAILED = 'REDEEM_WITHDRAW_FAILED';
