export const REGISTER_SUCCESSFUL = 'REGISTER_SUCCESSFUL';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESSFUL = 'USER_LOGIN_SUCCESSFUL';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
