export const REGISTER_SUCCESSFUL = 'REGISTER_SUCCESSFUL';
export const REGISTER = 'REGISTER';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESSFUL = 'USER_LOGIN_SUCCESSFUL';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_COUNTRIES_SUCCESSFUL = 'FETCH_COUNTRIES_SUCCESSFUL';
export const FETCH_COUNTRIES_FAILED = 'FETCH_COUNTRIES_FAILED';

export const FETCH_REDEEM_CONFIGS = 'FETCH_REDEEM_CONFIGS';
export const FETCH_REDEEM_CONFIGS_SUCCESSFUL =
  'FETCH_REDEEM_CONFIGS_SUCCESSFUL';
export const FETCH_REDEEM_CONFIGS_FAILED = 'FETCH_REDEEM_CONFIGS_FAILED';

export const REDEEM_WITHDRAW = 'REDEEM_WITHDRAW';
export const REDEEM_WITHDRAW_SUCCESSFUL = 'REDEEM_WITHDRAW_SUCCESSFUL';
export const REDEEM_WITHDRAW_FAILED = 'REDEEM_WITHDRAW_FAILED';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESSFUL = 'FETCH_USER_SUCCESSFUL';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';

export const FETCH_WITHDRAWALS = 'FETCH_WITHDRAWALS';
export const FETCH_WITHDRAWALS_SUCCESSFUL = 'FETCH_WITHDRAWALS_SUCCESSFUL';
export const FETCH_WITHDRAWALS_FAILED = 'FETCH_WITHDRAWALS_FAILED';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_SUCCESSFUL = 'USER_LOGOUT_SUCCESSFUL';
export const USER_LOGOUT_FAILED = 'USER_LOGOUT_FAILED';

export const FETCH_AGENTS = 'FETCH_AGENTS';
export const FETCH_AGENTS_SUCCESSFUL = 'FETCH_AGENTS_SUCCESSFUL';
export const FETCH_AGENTS_FAILED = 'FETCH_AGENTS_FAILED';

export const COLLECT_WASTE = 'COLLECT_WASTE';
export const COLLECT_WASTE_SUCCESSFUL = 'COLLECT_WASTE_SUCCESSFUL';
export const COLLECT_WASTE_FAILED = 'COLLECT_WASTE_FAILED';

export const FETCH_PLASTIC_TYPES = 'FETCH_PLASTIC_TYPES';
export const FETCH_PLASTIC_TYPES_SUCCESSFUL = 'FETCH_PLASTIC_TYPES_SUCCESSFUL';
export const FETCH_PLASTIC_TYPES_FAILED = 'FETCH_PLASTIC_TYPES_FAILED';
